galaxy_info:
  author: Musee Ullah
  description: Install and configure SSSD for system-level LDAP authentication
  company: FireEye, Inc.
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
    - trusty
    - utopic
    - vivid
  - name: Debian
    versions:
    - jessie
    - wheezy
  galaxy_tags:
    - authentication
dependencies: []
